# @package _global_

defaults:
  - /train # define in code
  - /model@model: cocap
  - /dataset@train_dataloader.dataset: vatex
  - /dataset@val_dataloader.dataset: vatex
  - /exp/train/base
  - _self_

trainer:
  default_root_dir: "./logs/vatex_captioning"
